FROM node:lts as builder

WORKDIR /app
COPY webui webui

WORKDIR /app/webui
RUN npm config set update-notifier false && npm install && npm install cors && npm run build-prod

FROM nginx:stable

COPY --from=builder /app/webui/dist /usr/share/nginx/html
